PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,

    mfa_enabled INTEGER NOT NULL DEFAULT 0,
    totp_secret TEXT,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login DATETIME,

    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until DATETIME
);

CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    token TEXT NOT NULL UNIQUE,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,

    active INTEGER NOT NULL DEFAULT 1,

    FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);